# Generated by Django 3.1.6 on 2021-03-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenciapago',
            old_name='pago',
            new_name='pago_bool',
        ),
    ]
