# Generated by Django 3.1.6 on 2021-03-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0002_auto_20210330_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciapago',
            name='monto_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto de Pago'),
        ),
    ]
