# Generated by Django 3.1.6 on 2021-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0004_auto_20210331_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeudas',
            name='deuda_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Deuda Acumulada'),
        ),
    ]
