# Generated by Django 3.1.6 on 2021-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0005_auto_20210331_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciapago',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Deuda'),
        ),
    ]
