# Generated by Django 3.1.6 on 2021-03-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0006_referenciapago_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenciapago',
            name='deuda',
        ),
    ]
