# Generated by Django 3.1.6 on 2021-04-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0007_remove_referenciapago_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeudas',
            name='deuda_ocumulada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Deuda'),
        ),
    ]
