# Generated by Django 3.1.6 on 2021-04-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0008_registrodeudas_deuda_ocumulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeudas',
            name='deuda_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Deuda Acumulada'),
        ),
    ]
