# Generated by Django 3.1.6 on 2021-04-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0009_auto_20210402_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodeudas',
            options={'ordering': ['apartamento'], 'verbose_name': 'Registro Deuda', 'verbose_name_plural': 'Registro Deudas'},
        ),
    ]
