# Generated by Django 3.1.6 on 2021-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0010_auto_20210406_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeudas',
            name='deuda_ocumulada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Deuda Acumulada'),
        ),
        migrations.AlterField(
            model_name='registrodeudas',
            name='deuda_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Deuda Pagar'),
        ),
    ]
