# Generated by Django 3.1.6 on 2021-04-26 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(blank=True, choices=[('0001-0010', '0001-0010'), ('0011-0020', '0011-0020'), ('0021-0030', '0021-0030'), ('0031-0040', '0031-0040'), ('0041-0050', '0041-0050')], max_length=9, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Codigos de Egresa',
                'verbose_name_plural': 'Codigos Egreso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Corte_mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mes', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, unique=True, verbose_name='Mes')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Fecha de Inicio ')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha de Fin')),
                ('monto_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto total de egreso ')),
                ('monto_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto total de ingreso ')),
                ('reserva', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reserva')),
                ('cerrar_mes', models.BooleanField(default=False, verbose_name='Cierre Mes')),
            ],
            options={
                'verbose_name': 'Administracion del Mes',
                'verbose_name_plural': 'Cierre de Mes',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto a pagar ')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('deuda', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Deuda Acumulada')),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total a pagar')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apart_reporte', to='edificio.apartamento', verbose_name='Apartamento')),
                ('corte_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.corte_mes', verbose_name='Administracion del Mes ')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_ingreso', models.CharField(choices=[('1', 'Fijo'), ('2', 'Comunes'), ('3', 'Otros Ingreso')], max_length=3, verbose_name='Tipo de Ingreso')),
                ('ingreso', models.CharField(max_length=50, verbose_name='Ingreso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Texto')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha ')),
                ('corte_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_mes', to='administracion.corte_mes', verbose_name='Administracion del Mes ')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_egreso', models.CharField(blank=True, choices=[('1', 'Fijo'), ('2', 'Comunes'), ('3', 'Otros Gastos')], max_length=3, verbose_name='Tipo de Egreso')),
                ('egreso', models.CharField(blank=True, max_length=50, verbose_name='Egreso')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto a Pagar')),
                ('monto_dolar', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto en Dolar')),
                ('precio_dolar', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Precio del dolar')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha ')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.codigoacceso', verbose_name='Codigo de Egreso')),
                ('corte_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egreso_mes', to='administracion.corte_mes', verbose_name='Administracion del Mes ')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
            },
        ),
    ]
