# Generated by Django 3.1.6 on 2021-03-27 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte_mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mes', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, unique=True, verbose_name='Mes')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Fecha de Inicio ')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha de Fin')),
                ('monto_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto total de egreso ')),
                ('monto_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto total de ingreso ')),
                ('reserva', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Reserva')),
                ('cerrar_mes', models.BooleanField(default=False, verbose_name='Cierre Mes')),
            ],
            options={
                'verbose_name': 'Administracion del Mes',
                'verbose_name_plural': 'Cierre de Mes',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto a pagar ')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('deuda', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Deuda Ocumulada')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio.apartamento', verbose_name='Apartamento')),
                ('corte_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.corte_mes', verbose_name='Administracion del Mes ')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_ingreso', models.CharField(choices=[('1', 'Ingreso Fijo'), ('2', 'Ingreso Comunes'), ('3', 'Otros Ingreso')], max_length=3, verbose_name='Tipo de Ingreso')),
                ('ingreso', models.CharField(max_length=50, verbose_name='Ingreso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Texto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha ')),
                ('corte_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_mes', to='administracion.corte_mes', verbose_name='Administracion del Mes ')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_egreso', models.CharField(choices=[('1', 'Gasto Fijo'), ('2', 'Gasto Comunes'), ('3', 'Otros Gastos')], max_length=3, verbose_name='Tipo de Egreso')),
                ('egreso', models.CharField(max_length=50, verbose_name='Egreso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Texto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha ')),
                ('corte_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egreso_mes', to='administracion.corte_mes', verbose_name='Administracion del Mes ')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
            },
        ),
    ]
