# Generated by Django 3.1.6 on 2021-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte_mes',
            name='nota',
            field=models.TextField(blank=True, verbose_name='Anotacion'),
        ),
    ]
