# Generated by Django 3.1.6 on 2021-03-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0004_auto_20210330_0038'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apart_reporte', to='edificio.apartamento', verbose_name='Apartamento'),
        ),
    ]
