# Generated by Django 3.1.6 on 2021-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='tipo_egreso',
            field=models.CharField(choices=[('1', 'Fijo'), ('2', 'Comunes'), ('3', 'Otros Gastos')], max_length=3, verbose_name='Tipo de Egreso'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_ingreso',
            field=models.CharField(choices=[('1', 'Fijo'), ('2', 'Comunes'), ('3', 'Otros Ingreso')], max_length=3, verbose_name='Tipo de Ingreso'),
        ),
    ]
