# Generated by Django 3.1.6 on 2021-03-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20210329_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte_mes',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=10, unique=True, verbose_name='Mes'),
        ),
    ]
