# Generated by Django 3.1.6 on 2021-03-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20210329_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total a pagar'),
        ),
        migrations.AlterField(
            model_name='corte_mes',
            name='mes',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, unique=True, verbose_name='Mes'),
        ),
    ]
