# Generated by Django 3.1.6 on 2021-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210329_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto a pagar '),
        ),
    ]
