# Generated by Django 3.1.6 on 2021-03-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20210330_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte_mes',
            name='reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reserva'),
        ),
    ]
