# Generated by Django 3.1.6 on 2021-04-26 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('edificio', models.CharField(max_length=10, verbose_name='Torres')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificio',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=20, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('apartamento', models.CharField(max_length=4, unique=True, verbose_name='Apartamento')),
                ('piso', models.PositiveIntegerField(verbose_name='Piso')),
                ('torre', models.CharField(choices=[('1', 'Torre A'), ('2', 'Torre B'), ('3', 'Alquiler')], max_length=4, verbose_name='Torres')),
                ('esquina', models.CharField(blank=True, max_length=10, verbose_name='Esquina')),
                ('alicuota', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Alicuota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_apart', to='edificio.propietario', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
    ]
