# Generated by Django 3.1.6 on 2021-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='alicuota',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Alicuota'),
        ),
    ]
