# Generated by Django 3.1.6 on 2021-03-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0003_auto_20210329_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_apart', to='edificio.propietario', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='torre',
            field=models.CharField(choices=[('1', 'Torre A'), ('2', 'Torre B'), ('3', 'Alquiler')], max_length=1, verbose_name='Torres'),
        ),
    ]
